### ISSUE TITLE
Does Faiss wrapper support Linux?

### ISSUE THREAD

**Issue by RockNHawk** [AIFramework/AIFrameworkOpen#3]
It seems that `faiss_c.dll` is officially a library and this project is not wrapped in C++, 
Can I simply put `libfaiss_c.so` into the runtimes directory to make the project cross-platform?

https://github.com/AIFramework/AIFrameworkOpen/blob/527eb04d63efefd9eeec5556aac3cf8f7044918e/src/AI.Faiss/FaissIndex.cs

**Comment by zaharPonimash** [comment]
Hello!
I developed this for Windows, but there are plans to make it cross-platform.
